name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      build_matrix_path: firmware/build.yaml  # 必須包含路徑
      config_path: firmware/config
